### ISSUE TITLE
can't join notes with triplet timing snap

### ISSUE THREAD

**Issue by jummy0** [towai/TromboneCharter#4] opened 2022-11-16 04:23 UTC
i can't join two notes/slides while using a triplet timing snap (e.g. 1/3, 1/6, 1/12), i assume due to rounding errors.

**Comment by towai** [comment] 2023-09-17 00:11
I haven't ever managed to reproduce this (at some settings it's harder, but still doable due to a small amount of leeway I added in to account for float error), but if you can test the project in the Godot editor / build it yourself, try and see if the latest commits resolve the issue.

**Comment by towai** [comment] 2023-12-03 01:18
i didn't close this at the time because i didn't feel right doing it without a release that someone could just download and run, but now that there's a github action auto-building and posting artifacts with each push i feel OK closing it. you can download the latest debug build here (at time of writing) → https://github.com/towai/TromboneCharter/actions/runs/7073708722

**Closed as completed by towai** 2023-12-03 01:18 UTC
